name: Run Full Scan (DAST) with ZAP
on: [push]
jobs:
    zap_scan:
        runs-on: ubuntu-latest
        name: Scan the webapplication
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 1
                ref: main
          - name: ZAP Scan
            uses: zaproxy/action-baseline@v0.14.0
            continue-on-error: true
            with:
              docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
              target: 'http://testphp.vulnweb.com/'
              rules_file_name: '.zap/rules.tsv'
              cmd_options: '-a'
